spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bar?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wang741
    initialization-mode: always
